### ISSUE TITLE
failed to integrate with vue-cli-service/typescript/babel/typescript/jest

### ISSUE THREAD

**Issue by bruceauyeung** [hustcc/jest-electron#19]
my electron app was created via `vue create xxx` and `vue add electron-builder`
what i chosed for my app:
~~~
Use class-style component syntax: choose y
Use Babel alongside TypeScript: choose y
Use history mode for router: choose n
Pick a CSS pre-processor: choose less              
Pick a linter / formatter config choose: eslint + prettier    
Pick additional lint features: choose Lint on save
Pick a unit testing solution: choose jest             
Pick a E2E testing solution: choose cypress            
Where do you prefer placing config: choose In dedicated config files
~~~

now i am trying to unit test my common modules which can only run within electron processes. 

i have already installed `jest-electron`, my `jest.config.js`:
~~~js
const deepmerge = require('deepmerge');
const defaultPreset = require('@vue/cli-plugin-unit-jest/presets/typescript-and-babel/jest-preset');

module.exports = deepmerge(defaultPreset, {
  verbose: true,
  runner: 'jest-electron/runner',
  testEnvironment: 'jest-electron/environment',
});
console.log(module.exports);
~~~

logged in as root, run `yarn test:unit`

outputs of  the last log line:
>yarn run v1.19.0
>$ vue-cli-service test:unit
>{
>  moduleFileExtensions: [ 'js', 'jsx', 'json', 'vue', 'ts', 'tsx' ],
>  transform: {
>    '^.+\\.vue$': '/root/icenter-next/node_modules/vue-jest/vue-jest.js',
>    '.+\\.(css|styl|less|sass|scss|svg|png|jpg|ttf|woff|woff2)$': '/root/icenter-next/node_modules/jest-transform-stub/index.js',
>    '^.+\\.jsx?$': '/root/icenter-next/node_modules/babel-jest/build/index.js',
>    '^.+\\.tsx?$': '/root/icenter-next/node_modules/ts-jest/dist/index.js'
>  },
>  transformIgnorePatterns: [ '/node_modules/' ],
>  moduleNameMapper: { '^@/(.*)$': '<rootDir>/src/$1' },
>  testEnvironment: 'jest-electron/environment',
>  snapshotSerializers: [ 'jest-serializer-vue' ],
>  testMatch: [ '\*\*/tests/unit/\*\*/\*.spec.[jt]s?(x)', '\*\*/__tests__/\*.[jt]s?(x)' ],
>  testURL: 'http://localhost/',
>  watchPlugins: [
>    '/root/icenter-next/node_modules/jest-watch-typeahead/filename.js',
>    '/root/icenter-next/node_modules/jest-watch-typeahead/testname.js'
>  ],
>  globals: { 'ts-jest': { babelConfig: true } },
>  verbose: true,
>  runner: 'jest-electron/runner'
>}
>

unluckily, after those logs , `yarn test:unit` hanged out.
in `/var/log/messages` there is a related error:
>kernel: [ 4037.805779] traps: electron[22011] trap int3 ip:5581e0f03755 sp:7ffcc0581af0 error:0

i am wondering maybe it's related to sandbox of electron, but i don't know how to tell `jest-electron` to lauch `electron` with parameter `--no-sandbox`

i am stuck here for almost a whole day, please help me out, thanks !

jest-electron: 0.1.11
electron: 6.1.4
vue-cli-plugin-electron-builder: 1.4.3
@vue/cli-plugin-unit-jest: 4.0.5
os: centos 7.4

**Comment by bruceauyeung** [comment]
manually edit `node_modules/jest-electron/lib/electron/proc/index.js`, pass `--no-sandbox` to spawned electron child process, and problem solved:
~~~js
    Electron.prototype.create = function () {
        return __awaiter(this, void 0, void 0, function () {
            var _this = this;
            return __generator(this, function (_a) {
                return [2 /*return*/, new Promise(function (resolve, reject) {
                        // electron starter
                        var entry = path.join(__dirname, '../main/index');
                        var args = ['--no-sandbox', entry];
                        var proc = child_process_1.spawn(electron, args, {
                            stdio: ['ipc'],
                            env: __assign(__assign({}, process.env), { DEBUG_MODE: _this.debugMode ? 'true' : '', CONCURRENCY: "" + _this.concurrency })
                        });
// codes omitted
                    })];
            });
        });
    };

~~~

would you like to add some configurations for this kind of purpose ?

**Comment by hustcc** [comment]
what's the meaning of --no-sandbox

**Comment by bruceauyeung** [comment]
`--no-sandbox` disables electron's sandbox mechanism. 
since electron V6,   electron enables zygote sandboxing via chrome-sandbox binary and suid/userns

>\# google-chrome
>[29357:29357:0107/143556.325965:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

**Comment by hustcc** [comment]
I do not know why the error related with sandbox?

**Comment by bruceauyeung** [comment]
electron apps can only run as root with `--no-sandbox`.

https://electronjs.org/docs/api/sandbox-option
IIUC, with `--no-sandbox` javascript codes running in renderer process may harm the system.

quoted from https://answers.microsoft.com/en-us/skype/forum/all/disable-electronchrome-sandboxing-on-linux/0260e3b1-5fa0-49ba-9854-dde1c040e249
>Electron default sandboxing isn't well accepted, check out number of linked issues at https://github.com/electron/electron/issues/17972. In general many electron applications now disable sandboxing by default, even VSCode did so https://github.com/microsoft/vscode/pull/81096.

i suggest that `jest-electron` provide a mechanism to let user to choose
