### ISSUE TITLE
lib electron-util can't be used in process spawned by jest-electron

### ISSUE THREAD

**Issue by bruceauyeung** [hustcc/jest-electron#20]
`electron-util` can only run in electron processes ( both main and  renderer processes)
`jest-electron` is designed to run all tests in electron process, but the following jest test failed with error:

~~~js
//file: electron.spec.js
test('Window Loads Properly', async () => {
  expect(process.type).toBe('renderer');
  try {
    const { is } = require('electron-util');
  } catch (e) {
    expect(e).toBe(null);
  }
});

~~~

error:
>
>FAIL  tests/unit/electron.spec.js
>  ● Test suite failed to run
>
>      ● Window Loads Properly
>
>        expect(received).toBe(expected) // Object.is equality
>
>        Expected: null
>        Received: [TypeError: Cannot create proxy with a non-object as target or handler]
>
>           7 |     const { is } = require('electron-util');
>           8 |   } catch (e) {
>        >  9 |     expect(e).toBe(null);
>             |               ^
>          10 |   }
>          11 |   //
>          12 |   //
>
>      at Object.<anonymous> (tests/unit/electron.spec.js:9:15)
>Test Suites: 1 failed, 1 total
>Tests:       0 total
>Snapshots:   0 total
>Time:        3.329s
>Ran all test suites.
>error Command failed with exit code 1.

`Cannot create proxy with a non-object as target or handler` means failed to require electron module.
`electron-util/source/api.js` source code quoted from github repo:
~~~js
'use strict';
const electron = require('electron');

module.exports = new Proxy(electron, {
	get: (target, property) => target[property] || (target.remote ? target.remote[property] : undefined)
});
~~~

env infos:
jest-electron: 0.1.11
electron: 6.1.4
vue-cli-plugin-electron-builder: 1.4.3
@vue/cli-plugin-unit-jest: 4.0.5
os: centos 7.4

**Comment by hustcc** [comment]
run test case of electron app in electron. I'm not sure if there's a problem.

But when i run the test cases in pure jest with non jest-electron, Error is also occurred

**Comment by bruceauyeung** [comment]
@hustcc  do you mean that test case  doesn't run in a real electron process with jest-electron as runner and testEnvironment ?
that test case failed with pure jest ,so i started to find a solution and found `jest-electron`, `jest-electron` states it's `The easiest way to run and debug test cases in electron with jest`, so  i expect that jest-electron is the problem solver

**Comment by bruceauyeung** [comment]
@hustcc 
quoted from https://github.com/facebook/jest/issues/3698#issuecomment-537980901
>It is a costom jest runner, the runner will receive the test data from jest, then send them into electron renderer thread, run cases, and send test results back to jest.

what is `the test data` mentioned above ?  do you mean the jest callback function ?
~~~js
async () => {
}
~~~

**Comment by bruceauyeung** [comment]
@hustcc 

~~~js
jest.setTimeout(100000);

test('Window Loads Properly',  () => {

  expect(process.type).toBe('renderer'); // true
  try{
    const electron = require('electron');
    console.log(`${typeof electron}`)  // string
                                //value is '/root/icenter-next/node_modules/electron/dist/electron'
  }catch(e){
    console.log(e)
  }
  try{
    const {ipcRenderer} = require('electron');
    console.log(`${typeof ipcRenderer}`)  // undefined
  }catch(e){
    console.log(e)
  }
  try{
    const exit = require('exit');
    console.log(`${typeof exit}`)  // function
  }catch(e){
    console.log(e)
  }
  try {
    const { is } = require('electron-util');
  } catch (e) {
    console.log(e)
  }
});

~~~

**Comment by bruceauyeung** [comment]
@hustcc 
thanks to https://github.com/electron/electron/issues/7300#issuecomment-248773783
finally i figured out how to `require` `electron-util` module / `electron` module, it looks like some other `require` conflicts with  `globalThis.require`
~~~js

jest.setTimeout(100000);
test('Window Loads Properly',  () => {
  expect(process.type).toBe('renderer');
  try{
    const electron = window.require('electron');  // use window.require instead of require
    console.log(`${typeof electron}`)
    console.log(`${electron}`)
  }catch(e){
    console.log(e)
  }
  try {
    const { is } = globalThis.require('electron-util'); // use globalThis.require instead of require
    console.log(`${is.renderer}`) 
  } catch (e) {
    console.log(e)
  }
});

~~~

**Comment by hustcc** [comment]
is the problem solved?

**Comment by bruceauyeung** [comment]
currently i have to say jest tests are NOT run within a real electron renderer process.

i checked `electron`'s source code, and indeed `electron` exports module path (a string):
~~~js
function getElectronPath () {
  if (fs.existsSync(pathFile)) {
    var executablePath = fs.readFileSync(pathFile, 'utf-8')
    if (process.env.ELECTRON_OVERRIDE_DIST_PATH) {
      return path.join(process.env.ELECTRON_OVERRIDE_DIST_PATH, executablePath)
    }
    return path.join(__dirname, 'dist', executablePath)
  } else {
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  }
}

module.exports = getElectronPath()
~~~
that's why within an ordinary node process `require('electron')` returns a string. real `electron` process 
looks like have done magic things before user javascript code being run, so we can `require('electron')` as we expected.

another diff between `jest-electron` and real `electron renderer` process:
with `jest-electron`,   `require === globalThis.require` is `false`, 
within a real electron process, `require === globalThis.require` is `true`. (tested in an electron app's devtools)

so i think ,can `jest-electron` lauch a real electron process to run tests ?

**Comment by bruceauyeung** [comment]
after some digging, i have already figured out why `require('electron')` returns module path instead of module itself. the root cause is `jest` has its own `require` implementation and it overwrites electron's `require` in each test files

closing because the problem has already been solved.
