### ISSUE TITLE
source code lines should be printed when test cases failed 

### ISSUE THREAD

**Issue by bruceauyeung** [hustcc/jest-electron#23]
when test cases fail to run,  source code lines are printed into `jest` console, but in `jest-electron` window(`DEBUG_MODE` is set to `true`) only have stack traces, less intuitive than `jest`.
![1](https://user-images.githubusercontent.com/1210201/72511296-e579ec00-3885-11ea-973a-76e4047a8db7.JPG)

**Comment by hustcc** [comment]
help to give a pr?

**Comment by bruceauyeung** [comment]
sure , happy to do !
