### ISSUE TITLE
devTools is not opened in jest-electron window in debug mode

### ISSUE THREAD

**Issue by bruceauyeung** [hustcc/jest-electron#25]
I noticed that devTools is supposed to be opened in ` jest-electron` window if `DEBUG_MODE` is true.
https://github.com/hustcc/jest-electron/blob/master/src/electron/main/window-pool.ts#L125-L128

and `jest-electron` indeed  open devTools on windows 7, but unfortunately  NOT  on my centos 7 box. 
i tried to figure out what's the problem and did some tests on my centos 7 box with `electron 6.1.4`:

1. i run `jest-electron` as root.
2. when i run `electron` directly without any arguments,  i can press `CTRL+SHIFT+I` to open devtools in the electron window.
3. when i open my own electron application,  i can also press  `CTRL+SHIFT+I` to open devtools, both with development mode or with built binary .
4. but in `jest-electron` window, devtools can not be opened neither via pressing  `CTRL+SHIFT+I`
 nor via clicking menu item `view -> Toggle Developer Tools`.

there is a similar  `electron`'s bug report related with openDevTools: https://github.com/electron/electron/issues/20069   ,
but i am wondering that  the problem i encountered has the same root cause with it because of my number 2 test.

any ideas ?

**Comment by hustcc** [comment]
sorry, I do not know. I haven't used window / linux for three years~

**Comment by hustcc** [comment]
Can help to test in your pc follow https://github.com/electron/electron/issues/20069#issuecomment-586642795
