### ISSUE TITLE
Out of date NPM package

### ISSUE THREAD

**Issue by lucas-jones** [hustcc/jest-electron#26]
Hey! Awesome library. I've noticed the `JEST_ELECTRON_NO_SANDBOX` commit hasn't been deployed/released to NPM

Wondering if you could deploy latest version :)

**Comment by hustcc** [comment]
> Hey! Awesome library. I've noticed the `JEST_ELECTRON_NO_SANDBOX` commit hasn't been deployed/released to NPM
> 
> Wondering if you could deploy latest version :)

I will update the electron version to latest, then release new npm version.

**Comment by hustcc** [comment]
v0.1.12

https://github.com/hustcc/jest-electron/releases/tag/v0.1.12
