### ISSUE TITLE
Jest not starting in CI on ubuntu

### ISSUE THREAD

**Issue by Prior99** [hustcc/jest-electron#27]
When trying to use XVFB to execute the tests on ubuntu in CI, Jest never starts up. Is there any way to get this to work on Linux, not just Mac?

**Comment by hustcc** [comment]
Are there any error log? Why you need run on linux?

**Comment by Prior99** [comment]
I need it to run on Linux, because I am using Gitlab CI.
As mentioned, there are no logs. Instead, Jest just hangs. I partially
fixed this by manually patching the package from NPM until #26 is resolved
and installing the OS electron dependencies.
I think the main issue here is that this package hides all errors from
electron. Perhaps the output from electron could be written into a log file
for better debugging?

**Comment by Prior99** [comment]
I debugged this today and figured out, that in docker the IPC shared memory is limited.
By providing electron the flag `--disable-dev-shm-usage`, hangups this can be prevented.
I created a PR documenting this and adding a corresponding environment variable.

**Comment by hustcc** [comment]
merged and released https://github.com/hustcc/jest-electron/releases/tag/v0.1.12
