### ISSUE TITLE
How does this project compare with https://github.com/facebook-atom/jest-electron-runner?

### ISSUE THREAD

**Issue by neojski** [hustcc/jest-electron#33]
I've been using https://github.com/facebook-atom/jest-electron-runner so far but I've found your project when I was trying to run my tests on github CI and:
```diff
- runs-on: ubuntu-latest
+ runs-on: macOS-latest
```
helped! Do you have a short summary of differences between your project and facebook's jest-electron-runner?

**Comment by hustcc** [comment]
See [here](https://github.com/jest-community/awesome-jest/pull/66).
