### ISSUE TITLE
Sass support

### ISSUE THREAD

**Issue by SzymonGalazka** [hustcc/jest-electron#34]
Hello,

Is there a way to bring .scss support with the current setup?
Running jest-electron within node 10-12 project (with appropriate node-sass version) shows the following error:
```
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (73)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
...
```

The project alone runs fine with scss support so I assume it is due to the old versions of e.x. Electron?

**Comment by hustcc** [comment]
you should add jest-sass-loader (write by yourself) into your project. ref: https://github.com/hustcc/jest-electron#related
