### ISSUE TITLE
Jest hangs-up in Ubuntu on GitHub Actions and WSL2

### ISSUE THREAD

**Issue by tentone** [hustcc/jest-electron#46]
Hello

Thanks a lot for the effort put into the project, i have some problems while running in WSL2 and on Github Actions CI.

The tests hang up without any errors, I have tried to run them in Windows and MacOS with success, but cannot run them under ubuntu both in github action and locally under WSL2.

I have tried some of chromium flags suggested in other issues and PR without success.

Thanks a lot!

![1](https://user-images.githubusercontent.com/9158354/143882557-5bd0270d-f865-4e4f-8409-106f46f96705.PNG)
![kernelk](https://user-images.githubusercontent.com/9158354/143882561-818504b8-3ec6-4210-bdac-a5379e673b39.PNG)

**Comment by Julien-Marcou** [comment]
I had the same issue trying to run the tests for PixiJS on WSL2.

I had to install VcXsrv on Windows.

I followed these tutorials:
- https://gist.github.com/caseywatts/9700b402b6b51d1d6af9f0b206739770
- https://www.beekeeperstudio.io/blog/building-electron-windows-ubuntu-wsl2

**Comment by tentone** [comment]
@Julien-Marcou The problem happens only in github actions. In windows i have no problem running it.

I have eventually moved to [this](https://github.com/kayahr/jest-electron-runner) fork of the jest-electron environment.

And evetually decided to move back to JSDOM.
